### PR TITLE
Feat meson - update docs to reflect meson build changes

### PR DESCRIPTION
**Pull request by jlcsf**
meson build changes to docs and netlify app testing

### CODE REVIEW

**Comment by papazof** [comment]
Meson instructions should be fine now. We need to check that all published docs are still relevant, ie. unikraft guide has a broken link to a build page, not sure where that's moved. Also, the binaries doc has broken links, we should fix these in the relevant repos' CI or remove them

**Comment by jlcsf** [comment]
I've pushed a commit regarding the legacy build system (cmake) to the docs - I think it's worth having these on the docs.

**Comment by papazof** [comment]
> I've pushed a commit regarding the legacy build system (cmake) to the docs - I think it's worth having these on the docs.

Yep, I agree, thought about it and just forgot :P. I'd say update the original building.md with the correct repo/anything you feel should be changed and move it to ie. user-guide/building-legacy.md so the docs structure is consistent.

>Also, I'm not too sure if we need to duplicate pages between quickstart and user guide? or maybe this is just me

I considered keeping them in one place but it's not unusual for a quickstart doc to have some tl;dr instructions I think. We should minimize duplication of building instructions in other docs though.

>Regarding the broken links and other links: if its possible to update them right now or soon, we should just add it to this PR and merge otherwise just start a new one

Agreed. We only need to make sure we have a working example with a hw plugin, either update Jetson with latest vAccel changes or use something else already up-to-date.

**Comment by jlcsf** [comment]
Updated to fit docs structure - but couldn't really figure out a way to get a working example with the hw plugin/jetson - might be better if someone who's working on that side can just quickly write up a page

**Comment by papazof** [comment]
Ok, thanks, LGTM and work on doc updates in a separate PR. The updates needed are not meson related anyway.

**Review by papazof — APPROVED** [review]

**Pull request merged**
